/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Myprog */

#ifndef _Included_Myprog
#define _Included_Myprog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Myprog
 * Method:    helib
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Myprog_helib
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
